# GAME PARAMETERS
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 640
SQUARES_NUM = 16
SQUARE_SIZE = SCREEN_WIDTH // SQUARES_NUM
SQUARE_COLOR_DARK = '#124F11'
SQUARE_COLOR_LIGHT = '#195D16'
SNAKE_START_LENGTH = 5
SNAKE_START_HEAD_CORDS = (0, 0)
SNAKE_COLOR = '#B57533'
SNAKE_HEAD_COLOR = '#FFBB36'
CLOCK_TICK_LIMIT = 6

UP = 2
DOWN = -2
LEFT = -1
RIGHT = 1